
package course.schedule.machine;

/**

 *

 * @author niharikamalviya

 */

public class homepageUI extends javax.swing.JFrame {

    /**

     * Creates new form homepageUI

     */

    public homepageUI() {

        initComponents();

    }

    /**

     * This method is called from within the constructor to initialize the form.

     * WARNING: Do NOT modify this code. The content of this method is always

     * regenerated by the Form Editor.

     */

    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          

    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        jComboBox7 = new javax.swing.JComboBox();

        jPanel2 = new javax.swing.JPanel();

        jLabel7 = new javax.swing.JLabel();

        ComboOne14 = new javax.swing.JComboBox();

        jLabel8 = new javax.swing.JLabel();

        jLabel9 = new javax.swing.JLabel();

        jLabel10 = new javax.swing.JLabel();

        ComboOne1 = new javax.swing.JComboBox();

        ComboOne2 = new javax.swing.JComboBox();

        ComboOne3 = new javax.swing.JComboBox();

        ComboOne4 = new javax.swing.JComboBox();

        ComboOne6 = new javax.swing.JComboBox();

        ComboOne7 = new javax.swing.JComboBox();

        ComboOne8 = new javax.swing.JComboBox();

        jLabel11 = new javax.swing.JLabel();

        jLabel12 = new javax.swing.JLabel();

        jLabel13 = new javax.swing.JLabel();

        jLabel14 = new javax.swing.JLabel();

        jLabel2 = new javax.swing.JLabel();

        jLabel15 = new javax.swing.JLabel();

        jLabel16 = new javax.swing.JLabel();

        ComboOne9 = new javax.swing.JComboBox();

        ComboOne = new javax.swing.JComboBox();

        ComboOne10 = new javax.swing.JComboBox();

        jLabel4 = new javax.swing.JLabel();

        ComboOne11 = new javax.swing.JComboBox();

        jLabel5 = new javax.swing.JLabel();

        ComboOne12 = new javax.swing.JComboBox();

        jLabel6 = new javax.swing.JLabel();

        ComboOne13 = new javax.swing.JComboBox();

        jLabel17 = new javax.swing.JLabel();

        jLabel18 = new javax.swing.JLabel();

        jComboBox1 = new javax.swing.JComboBox();

        jComboBox2 = new javax.swing.JComboBox();

        jComboBox3 = new javax.swing.JComboBox();

        jComboBox4 = new javax.swing.JComboBox();

        jComboBox5 = new javax.swing.JComboBox();

        jComboBox6 = new javax.swing.JComboBox();

        jComboBox8 = new javax.swing.JComboBox();

        jLabel3 = new javax.swing.JLabel();

        jLabel19 = new javax.swing.JLabel();

        jLabel20 = new javax.swing.JLabel();

        jLabel21 = new javax.swing.JLabel();

        jLabel22 = new javax.swing.JLabel();

        jLabel23 = new javax.swing.JLabel();

        jComboBox9 = new javax.swing.JComboBox();

        jLabel24 = new javax.swing.JLabel();

        jComboBox10 = new javax.swing.JComboBox();

        jPanel3 = new javax.swing.JPanel();

        jCheckBox3 = new javax.swing.JCheckBox();

        jCheckBox4 = new javax.swing.JCheckBox();

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        setTitle("WelCome to JHOP Course Selection ");

        setBackground(new java.awt.Color(0, 0, 255));

        setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select 

your Major", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, 

javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 

24), new java.awt.Color(0, 0, 255))); // NOI18N

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { 

"Biomedical Engineering", "Chemical and Biomolecular Engineering", "Civil 

Engineering", "Computer Engineering", "Electrical Engineering", "Engineering 

Mechanics", "Environmental Engineering", "General Engineering", "Materials 

Science and Engineering", "Mechanical Engineering", "Applied Mathematics and 

Statistics" }));

        javax.swing.GroupLayout jPanel1Layout = new 

javax.swing.GroupLayout(jPanel1);

        jPanel1.setLayout(jPanel1Layout);

        jPanel1Layout.setHorizontalGroup(            

jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(jPanel1Layout.createSequentialGroup()

                .addContainerGap()

                .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)

                .addContainerGap(409, Short.MAX_VALUE))

        );

        jPanel1Layout.setVerticalGroup(            

jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(jPanel1Layout.createSequentialGroup()

                .addGap(16, 16, 16)

                .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)

                .addContainerGap(57, Short.MAX_VALUE))

        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Choose 

AP Course", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, 

javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 

24), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel7.setText("AP Biology");

        ComboOne14.setModel(new javax.swing.DefaultComboBoxModel(new String[] { 

"N/A", "1", "2", "3", "4", "5", " " }));

        ComboOne14.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                ComboOne14ActionPerformed(evt);

            }

        });

        jLabel8.setText("AP Computer Science A");

        jLabel9.setText("AP Environmental Science");

        jLabel10.setText("AP Macroeconomics");

        ComboOne1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { 

"N/A", "1", "2", "3", "4", "5", " " }));

        ComboOne1.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                ComboOne1ActionPerformed(evt);

            }

        });

        ComboOne2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { 

"N/A", "1", "2", "3", "4", "5", " " }));

        ComboOne2.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                ComboOne2ActionPerformed(evt);

            }

        });

        ComboOne3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { 

"N/A", "1", "2", "3", "4", "5", " " }));

        ComboOne3.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                ComboOne3ActionPerformed(evt);

            }

        });

        ComboOne4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { 

"N/A", "1", "2", "3", "4", "5", " " }));

        ComboOne4.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                ComboOne4ActionPerformed(evt);

            }

        });

        ComboOne6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { 

"N/A", "1", "2", "3", "4", "5", " " }));

        ComboOne6.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                ComboOne6ActionPerformed(evt);

            }

        });

        ComboOne7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { 

"N/A", "1", "2", "3", "4", "5", " " }));

        ComboOne7.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                ComboOne7ActionPerformed(evt);

            }

        });

        ComboOne8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { 

"N/A", "1", "2", "3", "4", "5", " " }));

        ComboOne8.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                ComboOne8ActionPerformed(evt);

            }

        });

        jLabel11.setText("AP Computer Science A/B");

        jLabel12.setText("AP French Language");

        jLabel13.setText("AP German Language");

        jLabel14.setText("AP Italian Language");

        jLabel2.setText("AP Calculus AB");

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new 

java.awt.Color(0, 0, 0)));

        jLabel15.setText("AP Physics C (Mech)");

        jLabel16.setText("AP Physics C (E&M)");

        ComboOne9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { 

"N/A", "1", "2", "3", "4", "5", " " }));

        ComboOne9.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                ComboOne9ActionPerformed(evt);

            }

        });

        ComboOne.setModel(new javax.swing.DefaultComboBoxModel(new String[] { 

"N/A", "1", "2", "3", "4", "5", " " }));

        ComboOne.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                ComboOneActionPerformed(evt);

            }

        });

        ComboOne10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { 

"N/A", "1", "2", "3", "4", "5", " " }));

        ComboOne10.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                ComboOne10ActionPerformed(evt);

            }

        });

        jLabel4.setText("AP Calculus BC");

        ComboOne11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { 

"N/A", "1", "2", "3", "4", "5", " " }));

        ComboOne11.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                ComboOne11ActionPerformed(evt);

            }

        });

        jLabel5.setText("AP Microeconomics");

        ComboOne12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { 

"N/A", "1", "2", "3", "4", "5", " " }));

        ComboOne12.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                ComboOne12ActionPerformed(evt);

            }

        });

        jLabel6.setText("AP Chemistry");

        ComboOne13.setModel(new javax.swing.DefaultComboBoxModel(new String[] { 

"N/A", "1", "2", "3", "4", "5", " " }));

        ComboOne13.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                ComboOne13ActionPerformed(evt);

            }

        });

        jLabel17.setText("IB Physics");

        jLabel18.setText("IB Spanish (B or A2)");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { 

"N/A", "1", "2", "3", "4", "5", "6", "7", " " }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { 

"N/A", "1", "2", "3", "4", "5", "6", "7", " " }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { 

"N/A", "1", "2", "3", "4", "5", "6", "7", " " }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { 

"N/A", "1", "2", "3", "4", "5", "6", "7", " " }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { 

"N/A", "1", "2", "3", "4", "5", "6", "7", " " }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { 

"N/A", "1", "2", "3", "4", "5", "6", "7", " " }));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { 

"N/A", "1", "2", "3", "4", "5", "6", "7", " " }));

        jLabel3.setText("IB Biology");

        jLabel19.setText("IB Chemistry");

        jLabel20.setText("IB Computer Science");

        jLabel21.setText("IB French (B or A2)");

        jLabel22.setText("IB German (B or A2)");

        jLabel23.setText("IB Macroeconomics ");

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { 

"N/A", "1", "2", "3", "4", "5", "6", "7", " " }));

        jLabel24.setText("IB Microeconomics");

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] 

{ "N/A", "1", "2", "3", "4", "5", "6", "7", " " }));

        javax.swing.GroupLayout jPanel2Layout = new 

javax.swing.GroupLayout(jPanel2);

        jPanel2.setLayout(jPanel2Layout);

        jPanel2Layout.setHorizontalGroup(            

jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(jPanel2Layout.createSequentialGroup()

                .addContainerGap()

                

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

LEADING)

                    .addGroup(jPanel2Layout.createSequentialGroup()                        

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

LEADING)

                            .addGroup(jPanel2Layout.createSequentialGroup()                                

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

TRAILING)

                                    .addComponent(jLabel2)                                    

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

LEADING)

                                        .addComponent(jLabel6)

                                        .addComponent(jLabel4)

                                        .addComponent(jLabel7)))

                                .addGap(38, 38, 38))

                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, 

jPanel2Layout.createSequentialGroup()

                                .addComponent(jLabel10)                                

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))                        

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

LEADING)

                            .addComponent(ComboOne1, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)

                            .addComponent(ComboOne, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)

                            .addGroup(jPanel2Layout.createSequentialGroup()

                                .addGap(6, 6, 6)                                

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

LEADING)

                                    .addComponent(ComboOne3, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)

                                    .addComponent(ComboOne4, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)

                                    .addComponent(ComboOne2, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)))))

                    .addGroup(jPanel2Layout.createSequentialGroup()

                        .addComponent(jLabel8)                        

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

                        .addComponent(ComboOne6, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE))

                    .addComponent(jLabel14)

                    .addGroup(jPanel2Layout.createSequentialGroup()

                        .addComponent(jLabel9)                        

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)

                        .addComponent(ComboOne10, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE))

                    .addGroup(jPanel2Layout.createSequentialGroup()                        

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

LEADING)

                            .addComponent(jLabel5)

                            .addComponent(jLabel11)

                            .addComponent(jLabel12)

                            .addComponent(jLabel13))                        

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

LEADING)

                            .addGroup(jPanel2Layout.createSequentialGroup()

                                .addGap(6, 6, 6)                                

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

LEADING)

                                    .addComponent(ComboOne11, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)

                                    .addComponent(ComboOne12, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)

                                    .addComponent(ComboOne14, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)))

                            .addGroup(jPanel2Layout.createSequentialGroup()                                

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

LEADING)

                                    .addGroup(jPanel2Layout.createSequentialGroup()                                        

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)                                        

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

LEADING)

                                            .addComponent(ComboOne8, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)

                                            .addComponent(ComboOne7, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)))

                                    .addGroup(jPanel2Layout.createSequentialGroup()

                                        .addGap(6, 6, 6)

                                        .addComponent(ComboOne9, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)))

                                .addGap(60, 60, 60)                                

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

LEADING)

                                    .addComponent(jLabel3)

                                    .addComponent(jLabel19)

                                    .addComponent(jLabel20)

                                    .addComponent(jLabel21)

                                    .addComponent(jLabel22)

                                    .addComponent(jLabel23)

                                    .addComponent(jLabel24)

                                    .addComponent(jLabel17)

                                    .addComponent(jLabel18))

                                .addGap(128, 128, 128)                                

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

LEADING)

                                    .addComponent(jComboBox10, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)

                                    .addComponent(jComboBox9, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)

                                    .addComponent(jComboBox8, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)

                                    .addComponent(jComboBox6, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)

                                    .addComponent(jComboBox5, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)

                                    .addComponent(jComboBox4, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)

                                    .addComponent(jComboBox3, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)

                                    .addComponent(jComboBox2, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)

                                    .addComponent(jComboBox1, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)))))

                    .addGroup(jPanel2Layout.createSequentialGroup()                        

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

LEADING)

                            .addComponent(jLabel15)

                            .addComponent(jLabel16))

                        .addGap(57, 57, 57)

                        .addComponent(ComboOne13, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)))

                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, 

Short.MAX_VALUE))

        );

        jPanel2Layout.setVerticalGroup(            

jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(jPanel2Layout.createSequentialGroup()                

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

LEADING)

                    .addGroup(jPanel2Layout.createSequentialGroup()                        

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

BASELINE)

                            .addComponent(jLabel2)

                            .addComponent(ComboOne, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE))

                        

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)                        

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

BASELINE)

                            .addComponent(jLabel4)

                            .addComponent(ComboOne1, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE))                        

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)                        

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

BASELINE)

                            .addComponent(jLabel6)

                            .addComponent(ComboOne2, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE))

                        .addGap(10, 10, 10)                        

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

BASELINE)

                            .addComponent(jLabel7)

                            .addComponent(ComboOne3, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE))

                        .addGap(12, 12, 12)                        

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

BASELINE)

                            .addComponent(jLabel10)

                            .addComponent(ComboOne4, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE))                        

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)                        

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

BASELINE)

                            .addComponent(jLabel8)

                            .addComponent(ComboOne6, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE))

                        .addGap(10, 10, 10)                        

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

BASELINE)

                            .addComponent(ComboOne7, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)

                            .addComponent(jLabel11))                        

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)                        

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

BASELINE)

                            .addComponent(ComboOne8, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)

                            .addComponent(jLabel5))

                        .addGap(11, 11, 11)                        

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

LEADING)

                            .addComponent(jLabel9)

                            .addComponent(ComboOne10, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE))

                        .addGap(18, 18, 18)                        

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

LEADING)

                            .addComponent(jLabel12)

                            .addComponent(ComboOne9, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)))

                    .addGroup(jPanel2Layout.createSequentialGroup()

                        .addContainerGap()                        

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

BASELINE)

                            .addComponent(jLabel3)

                            .addComponent(jComboBox1, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE))                        

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)                        

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

BASELINE)

                            .addComponent(jLabel19)

                            .addComponent(jComboBox2, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE))

                        .addGap(18, 18, 18)

                        

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

BASELINE)

                            .addComponent(jLabel20)

                            .addComponent(jComboBox3, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE))

                        .addGap(18, 18, 18)                        

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

BASELINE)

                            .addComponent(jLabel21)

                            .addComponent(jComboBox4, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE))

                        .addGap(18, 18, 18)                        

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

BASELINE)

                            .addComponent(jLabel22)

                            .addComponent(jComboBox5, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE))

                        .addGap(18, 18, 18)                        

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

BASELINE)

                            .addComponent(jLabel23)

                            .addComponent(jComboBox6, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE))

                        .addGap(18, 18, 18)                        

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

LEADING)

                            .addComponent(jLabel24)

                            .addComponent(jComboBox8, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE))

                        .addGap(18, 18, 18)                        

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

LEADING)

                            .addComponent(jLabel17)

                            .addComponent(jComboBox9, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE))

                        .addGap(18, 18, 18)                        

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

LEADING)

                            .addComponent(jLabel18)

                            .addComponent(jComboBox10, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE))))                

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)                

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

BASELINE)

                    .addComponent(jLabel13)

                    .addComponent(ComboOne12, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE))                

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)                

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

BASELINE)

                    .addComponent(jLabel14)

                    .addComponent(ComboOne11, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE))                

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)                

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

BASELINE)

                    .addComponent(jLabel15)

                    .addComponent(ComboOne13, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE))                

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)                

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

BASELINE)

                    .addComponent(jLabel16)

                    .addComponent(ComboOne14, 

javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE))

                .addGap(0, 12, Short.MAX_VALUE))

        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Indicate 

any pre-professional track", 

javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, 

javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 

24), new java.awt.Color(0, 0, 255))); // NOI18N

        jCheckBox3.setText("jPre Med");

        jCheckBox4.setText("Pre Law");

        javax.swing.GroupLayout jPanel3Layout = new 

javax.swing.GroupLayout(jPanel3);

        jPanel3.setLayout(jPanel3Layout);

        jPanel3Layout.setHorizontalGroup(            

jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(jPanel3Layout.createSequentialGroup()

                .addContainerGap()                

.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.

LEADING)

                    .addComponent(jCheckBox3)

                    .addComponent(jCheckBox4))

                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, 

Short.MAX_VALUE))

        );

        jPanel3Layout.setVerticalGroup(            

jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(jPanel3Layout.createSequentialGroup()

                .addGap(14, 14, 14)

                .addComponent(jCheckBox3)

                .addGap(18, 18, 18)

                .addComponent(jCheckBox4)

                .addContainerGap(22, Short.MAX_VALUE))

        );

        jButton1.setText("Submit");

        javax.swing.GroupLayout layout = new 

javax.swing.GroupLayout(getContentPane());

        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(

            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(layout.createSequentialGroup()                

.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADIN

G)

                    .addGroup(layout.createSequentialGroup()

                        .addGap(39, 39, 39)

                        

.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADIN

G, false)

                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                            .addComponent(jPanel3, 

javax.swing.GroupLayout.Alignment.TRAILING, 

javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, 

Short.MAX_VALUE)))

                    .addGroup(layout.createSequentialGroup()

                        .addGap(356, 356, 356)

                        .addComponent(jButton1)))

                .addContainerGap(1231, Short.MAX_VALUE))

        );

        layout.setVerticalGroup(

            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(layout.createSequentialGroup()

                .addGap(46, 46, 46)

                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)                

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)                

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)

                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 

javax.swing.GroupLayout.DEFAULT_SIZE, 

javax.swing.GroupLayout.PREFERRED_SIZE)

                .addGap(18, 18, 18)

                .addComponent(jButton1)

                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, 

Short.MAX_VALUE))

        );

        jPanel2.getAccessibleContext().setAccessibleName("Please enter your AP/IB 

scores");

        pack();

    }// </editor-fold>                        

    private void ComboOne14ActionPerformed(java.awt.event.ActionEvent evt) {                                           

        // TODO add your handling code here:

    }                                          

    private void ComboOne1ActionPerformed(java.awt.event.ActionEvent evt) {                                          

        // TODO add your handling code here:

    }                                         

    private void ComboOne2ActionPerformed(java.awt.event.ActionEvent evt) {                                          

        // TODO add your handling code here:

    }                                         

    private void ComboOne3ActionPerformed(java.awt.event.ActionEvent evt) {                                          

        // TODO add your handling code here:

    }                                         

    private void ComboOne4ActionPerformed(java.awt.event.ActionEvent evt) {                                          

        // TODO add your handling code here:

    }                                         

    private void ComboOne6ActionPerformed(java.awt.event.ActionEvent evt) {                                          

        // TODO add your handling code here:

    }                                         

    private void ComboOne7ActionPerformed(java.awt.event.ActionEvent evt) {                                          

        // TODO add your handling code here:

    }                                         

    private void ComboOne8ActionPerformed(java.awt.event.ActionEvent evt) {                                          

        // TODO add your handling code here:

    }                                         

    private void ComboOne9ActionPerformed(java.awt.event.ActionEvent evt) {                                          

        // TODO add your handling code here:

    }                                         

    private void ComboOneActionPerformed(java.awt.event.ActionEvent evt) {                                         

        // TODO add your handling code here:

    }                                        

    private void ComboOne10ActionPerformed(java.awt.event.ActionEvent evt) {                                           

        // TODO add your handling code here:

    }                                          

    private void ComboOne11ActionPerformed(java.awt.event.ActionEvent evt) {                                           

        // TODO add your handling code here:

    }                                          

    private void ComboOne12ActionPerformed(java.awt.event.ActionEvent evt) {                                           

        // TODO add your handling code here:

    }                                          

    private void ComboOne13ActionPerformed(java.awt.event.ActionEvent evt) {                                           

        // TODO add your handling code here:

    }                                          

    /**

     * @param args the command line arguments

     */

    public static void main(String args[]) {

        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code 

(optional) ">

        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look 

and feel.

         * For details see 

http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 

         */

        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : 

javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(info.getClassName());

                    break;

                }

            }

        } catch (ClassNotFoundException ex) {            

java.util.logging.Logger.getLogger(homepageUI.class.getName()).log(java.util.loggin

g.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {            

java.util.logging.Logger.getLogger(homepageUI.class.getName()).log(java.util.loggin

g.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {            

java.util.logging.Logger.getLogger(homepageUI.class.getName()).log(java.util.loggin

g.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {            

java.util.logging.Logger.getLogger(homepageUI.class.getName()).log(java.util.loggin

g.Level.SEVERE, null, ex);

        }

        //</editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new homepageUI().setVisible(true);

            }

        });

    }

    // Variables declaration - do not modify                     

    private javax.swing.JComboBox ComboOne;

    private javax.swing.JComboBox ComboOne1;

    private javax.swing.JComboBox ComboOne10;

    private javax.swing.JComboBox ComboOne11;

    private javax.swing.JComboBox ComboOne12;

    private javax.swing.JComboBox ComboOne13;

    private javax.swing.JComboBox ComboOne14;

    private javax.swing.JComboBox ComboOne2;

    private javax.swing.JComboBox ComboOne3;

    private javax.swing.JComboBox ComboOne4;

    private javax.swing.JComboBox ComboOne6;

    private javax.swing.JComboBox ComboOne7;

    private javax.swing.JComboBox ComboOne8;

    private javax.swing.JComboBox ComboOne9;

    private javax.swing.JButton jButton1;

    private javax.swing.JCheckBox jCheckBox3;

    private javax.swing.JCheckBox jCheckBox4;

    private javax.swing.JComboBox jComboBox1;

    private javax.swing.JComboBox jComboBox10;

    private javax.swing.JComboBox jComboBox2;

    private javax.swing.JComboBox jComboBox3;

    private javax.swing.JComboBox jComboBox4;

    private javax.swing.JComboBox jComboBox5;

    private javax.swing.JComboBox jComboBox6;

    private javax.swing.JComboBox jComboBox7;

    private javax.swing.JComboBox jComboBox8;

    private javax.swing.JComboBox jComboBox9;

    private javax.swing.JLabel jLabel10;

    private javax.swing.JLabel jLabel11;

    private javax.swing.JLabel jLabel12;

    private javax.swing.JLabel jLabel13;

    private javax.swing.JLabel jLabel14;

    private javax.swing.JLabel jLabel15;

    private javax.swing.JLabel jLabel16;

    private javax.swing.JLabel jLabel17;

    private javax.swing.JLabel jLabel18;

    private javax.swing.JLabel jLabel19;

    private javax.swing.JLabel jLabel2;

    private javax.swing.JLabel jLabel20;

    private javax.swing.JLabel jLabel21;

    private javax.swing.JLabel jLabel22;

    private javax.swing.JLabel jLabel23;

    private javax.swing.JLabel jLabel24;

    private javax.swing.JLabel jLabel3;

    private javax.swing.JLabel jLabel4;

    private javax.swing.JLabel jLabel5;

    private javax.swing.JLabel jLabel6;

    private javax.swing.JLabel jLabel7;

    private javax.swing.JLabel jLabel8;

    private javax.swing.JLabel jLabel9;

    private javax.swing.JPanel jPanel1;

    private javax.swing.JPanel jPanel2;

    private javax.swing.JPanel jPanel3;

    // End of variables declaration                   

}
