/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package course.schedule.machine;

import java.util.HashSet;
import java.util.ArrayList;
import scheduleGenerator.DbFiles.ManageTxtFiles;
import java.io.IOException;

/**
 *
 * @author niharikamalviya
 */
public class homepageUI extends javax.swing.JFrame {

    /**
     * Creates new form homepageUI
     */
    public homepageUI() {
       
        initComponents();
        try{
        RequiredCourseSet.createCategoryRequiredCourseLists();
        }
        catch(IOException a){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        major = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        premed = new javax.swing.JCheckBox();
        submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        credit = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        term = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        minor = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        takenCourse = new javax.swing.JTextField();
        addTakenCourses = new java.awt.Button();
        jLabel12 = new javax.swing.JLabel();
        errorMessage = new javax.swing.JLabel();
        accepted = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        errorMessageMajor = new javax.swing.JLabel();
        schedule = new javax.swing.JPanel();
        generatedImportantCourses = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        scheduleDisplayer = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        ibBio = new javax.swing.JComboBox();
        ibChem = new javax.swing.JComboBox();
        ibComp = new javax.swing.JComboBox();
        ibMath = new javax.swing.JComboBox();
        ibMacEcon = new javax.swing.JComboBox();
        ibMicEcon = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        ibPhys = new javax.swing.JComboBox();
        jLabel39 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        physElec = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        calcBC = new javax.swing.JComboBox();
        chem = new javax.swing.JComboBox();
        bio = new javax.swing.JComboBox();
        macEcon = new javax.swing.JComboBox();
        compA = new javax.swing.JComboBox();
        compAB = new javax.swing.JComboBox();
        micEcon = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        calcAB = new javax.swing.JComboBox();
        enviro = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        physMech = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        stat = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        QuitMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WelCome to JHOP Course Selection ");
        setBackground(new java.awt.Color(0, 0, 255));
        setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select your Major", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(0, 0, 255))); // NOI18N

        major.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please select one", "Biomedical Engineering", "Molecular and Cellular Biology", "Materials Science Engineering", "Biophysics" }));
        major.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                majorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(major, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(major, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Indicate if pre-med", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(0, 0, 255))); // NOI18N

        premed.setText("Pre Med");
        premed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                premedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(premed)
                .addGap(217, 217, 217))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(premed)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/course/schedule/machine/myJhu.PNG"))); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Approx. # of Credits Wanted This Term", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(0, 0, 255))); // NOI18N

        credit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12", "12.5", "13", "13.5", "14", "14.5", "15", "15.5", "16", "16.5", "17", "17.5", "18", "18.5", "19", "19.5" }));
        credit.setSelectedIndex(8);
        credit.setToolTipText("");
        credit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(credit, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(credit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Current Term", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(0, 0, 255))); // NOI18N

        term.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fall 2015", "Intersession 2015", "Spring 2015", "Summer 2015" }));
        term.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(term, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(term, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select your Minor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(0, 0, 255))); // NOI18N

        minor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "Math", "Computer Science Analysis", "Computer Science Systems", "Computer Science Applications" }));
        minor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(minor, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Classes Already Taken (Course Number)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(0, 0, 255))); // NOI18N

        takenCourse.setText("Example: AS.171.102 or 171.102");
        takenCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takenCourseActionPerformed(evt);
            }
        });
        takenCourse.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                takenCourseFocusGained(evt);
            }
        });

        addTakenCourses.setLabel("Add");
        addTakenCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTakenCoursesActionPerformed(evt);
            }
        });

        jLabel12.setText("Please add classes individually, and only enter the course number.");

        errorMessage.setForeground(new java.awt.Color(250, 0, 0));

        accepted.setForeground(new java.awt.Color(0, 150, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(takenCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(addTakenCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(accepted, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel12)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(addTakenCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(takenCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(accepted, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        label1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 0, 204));
        label1.setText("Please fill the form and click \"Submit\"");

        errorMessageMajor.setForeground(new java.awt.Color(250, 0, 0));

        schedule.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Your Schedule will appear below", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(0, 0, 255))); // NOI18N

        generatedImportantCourses.setToolTipText("");

        scheduleDisplayer.setEditable(false);
        scheduleDisplayer.setColumns(20);
        scheduleDisplayer.setRows(5);
        jScrollPane1.setViewportView(scheduleDisplayer);

        javax.swing.GroupLayout scheduleLayout = new javax.swing.GroupLayout(schedule);
        schedule.setLayout(scheduleLayout);
        scheduleLayout.setHorizontalGroup(
            scheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(generatedImportantCourses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        scheduleLayout.setVerticalGroup(
            scheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(generatedImportantCourses, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input AP / IB Scores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel33.setText("IB Physics");

        ibBio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "1", "2", "3", "4", "5", "6", "7", " " }));

        ibChem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "1", "2", "3", "4", "5", "6", "7", " " }));

        ibComp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "1", "2", "3", "4", "5", "6", "7", " " }));

        ibMath.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "1", "2", "3", "4", "5", "6", "7", " " }));

        ibMacEcon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "1", "2", "3", "4", "5", "6", "7", " " }));

        ibMicEcon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "1", "2", "3", "4", "5", "6", "7", " " }));

        jLabel34.setText("IB Biology");

        jLabel35.setText("IB Chemistry");

        jLabel36.setText("IB Computer Science");

        jLabel37.setText("IB Mathematics");

        jLabel38.setText("IB Macroeconomics ");

        ibPhys.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "1", "2", "3", "4", "5", "6", "7", " " }));

        jLabel39.setText("IB Microeconomics");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                            .addComponent(jLabel37)
                            .addComponent(jLabel38)
                            .addComponent(jLabel39)
                            .addComponent(jLabel33))
                        .addGap(125, 125, 125)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ibMacEcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ibMicEcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ibPhys, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ibMath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ibComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ibChem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ibBio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(ibBio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ibChem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(ibComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(ibMath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(ibMacEcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(ibMicEcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ibPhys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(0, 153, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("IB", jPanel8);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input AP / IB Scores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel7.setText("AP Biology");

        physElec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "1", "2", "3", "4", "5", " " }));
        physElec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                physElecActionPerformed(evt);
            }
        });

        jLabel8.setText("AP Computer Science A");

        jLabel9.setText("AP Environmental Science");

        jLabel10.setText("AP Macroeconomics");

        calcBC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "1", "2", "3", "4", "5", " " }));
        calcBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcBCActionPerformed(evt);
            }
        });

        chem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "1", "2", "3", "4", "5", " " }));
        chem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chemActionPerformed(evt);
            }
        });

        bio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "1", "2", "3", "4", "5", " " }));
        bio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bioActionPerformed(evt);
            }
        });

        macEcon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "1", "2", "3", "4", "5", " " }));
        macEcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                macEconActionPerformed(evt);
            }
        });

        compA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "1", "2", "3", "4", "5", " " }));
        compA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compAActionPerformed(evt);
            }
        });

        compAB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "1", "2", "3", "4", "5", " " }));
        compAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compABActionPerformed(evt);
            }
        });

        micEcon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "1", "2", "3", "4", "5", " " }));
        micEcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                micEconActionPerformed(evt);
            }
        });

        jLabel11.setText("AP Computer Science A/B");

        jLabel2.setText("AP Calculus AB");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setText("AP Physics C (Mech)");

        jLabel16.setText("AP Physics C (E&M)");

        calcAB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "1", "2", "3", "4", "5", " " }));
        calcAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcABActionPerformed(evt);
            }
        });

        enviro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "1", "2", "3", "4", "5", " " }));
        enviro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviroActionPerformed(evt);
            }
        });

        jLabel4.setText("AP Calculus BC");

        jLabel5.setText("AP Microeconomics");

        jLabel6.setText("AP Chemistry");

        physMech.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "1", "2", "3", "4", "5", " " }));
        physMech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                physMechActionPerformed(evt);
            }
        });

        jLabel25.setText("AP Statistics");

        stat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "1", "2", "3", "4", "5", " " }));
        stat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)))
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel25))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(physElec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(physMech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(micEcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enviro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(compAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(compA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(macEcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calcBC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calcAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(calcAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(calcBC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(chem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(macEcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(compA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(compAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(micEcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(enviro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(physMech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(physElec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(bio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("AP", jPanel2);
        jPanel2.getAccessibleContext().setAccessibleName("Please enter your AP/IB scores");

        jMenu1.setText("File");

        QuitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.META_MASK));
        QuitMenuItem.setText("Quit");
        QuitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(QuitMenuItem);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Reset");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(errorMessageMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(118, 118, 118)
                                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(schedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(errorMessageMajor)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)))
                .addComponent(schedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.getAccessibleContext().setAccessibleName("Classes Already Taken (Course #)");
        label1.getAccessibleContext().setAccessibleName("Please fill out the info below, then click 'Submit\"");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void majorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_majorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_majorActionPerformed

    private void creditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditActionPerformed

    private void termActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_termActionPerformed

    private void minorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minorActionPerformed

    private HashSet<HopkinsCourse> apib = new HashSet<HopkinsCourse>();
    
    public void addAPIB() //throws IOException
    {
        try{
        ManageTxtFiles.getAllCourses();
        }
        catch(IOException e){
    System.out.println("ERROR");    
        }
        
        //calc AB
        if (!(calcAB.getSelectedItem().toString().trim().equals(("N/A").trim())))
            if (Integer.parseInt(calcAB.getSelectedItem().toString()) == 5)
            {
                apib.add(HopkinsCourse.getCourse("110.108"));
            }
        
       //calc BC
        if (!(calcBC.getSelectedItem().toString().trim().equals(("N/A").trim())))
        {
            if (Integer.parseInt(calcBC.getSelectedItem().toString()) == 5)
            {
                apib.add(HopkinsCourse.getCourse("110.108"));
                apib.add(HopkinsCourse.getCourse("110.109"));
            }
            else if (Integer.parseInt(calcBC.getSelectedItem().toString()) == 3 || Integer.parseInt(calcBC.getSelectedItem().toString()) == 4)
            {
                apib.add(HopkinsCourse.getCourse("110.108"));
            }
        }
        
        //chemistry
        if (!(chem.getSelectedItem().toString().trim().equals(("N/A").trim())))
        {
            if (Integer.parseInt(chem.getSelectedItem().toString()) == 5)
            {
                apib.add(HopkinsCourse.getCourse("030.101"));
                apib.add(HopkinsCourse.getCourse("030.102"));
                apib.add(HopkinsCourse.getCourse("030.105"));
                apib.add(HopkinsCourse.getCourse("030.106"));
            }
            else if (Integer.parseInt(chem.getSelectedItem().toString()) == 4)
            {
                apib.add(HopkinsCourse.getCourse("030.100"));
                apib.add(HopkinsCourse.getCourse("030.105"));
            }
        }
        
        //bio
        if (!(bio.getSelectedItem().toString().trim().equals(("N/A").trim())))
        {
            if (Integer.parseInt(bio.getSelectedItem().toString()) == 5)
            {
                apib.add(HopkinsCourse.getCourse("020.151"));
                apib.add(HopkinsCourse.getCourse("020.152"));
                apib.add(HopkinsCourse.getCourse("020.153"));
                apib.add(HopkinsCourse.getCourse("020.154"));
            }
           
        }
        
        
        
         //Macroecon
        if (!(macEcon.getSelectedItem().toString().trim().equals(("N/A").trim())))
        {
            if (Integer.parseInt(macEcon.getSelectedItem().toString()) == 5)
            {
                apib.add(HopkinsCourse.getCourse("180.101"));
            }
           
        }
        
         //Microecon
        if (!(micEcon.getSelectedItem().toString().trim().equals(("N/A").trim())))
        {
            if (Integer.parseInt(micEcon.getSelectedItem().toString()) == 5)
            {
                apib.add(HopkinsCourse.getCourse("180.102"));
            }
           
        }
        
         //CompSci A
        if (!(compA.getSelectedItem().toString().trim().equals(("N/A").trim())))
        {
            if (Integer.parseInt(compA.getSelectedItem().toString()) == 5)
            {
                apib.add(HopkinsCourse.getCourse("600.107"));
            }
           
        }
        
        //CompSci AB
        if (!(compAB.getSelectedItem().toString().trim().equals(("N/A").trim())))
        {
            if (Integer.parseInt(compAB.getSelectedItem().toString()) == 5 || Integer.parseInt(compAB.getSelectedItem().toString()) == 4)
            {
                apib.add(HopkinsCourse.getCourse("600.107"));
            }
           
        }
       
        //Physics C Mech
        if (!(physMech.getSelectedItem().toString().trim().equals(("N/A").trim())))
        {
            if (Integer.parseInt(physMech.getSelectedItem().toString()) == 5 || Integer.parseInt(physMech.getSelectedItem().toString()) == 4)
            {
                apib.add(HopkinsCourse.getCourse("173.111"));
                apib.add(HopkinsCourse.getCourse("171.101"));
            }
           
        }
        
        //Physics C Electrical
        if (!(physElec.getSelectedItem().toString().trim().equals(("N/A").trim())))
        {
            if (Integer.parseInt(physElec.getSelectedItem().toString()) == 5 || Integer.parseInt(physElec.getSelectedItem().toString()) == 4)
            {
                apib.add(HopkinsCourse.getCourse("173.112"));
                apib.add(HopkinsCourse.getCourse("171.102"));
            }
           
        }
        
         //Statistic
        if (!(stat.getSelectedItem().toString().trim().equals(("N/A").trim())))
        {
            if (Integer.parseInt(stat.getSelectedItem().toString()) == 5 || Integer.parseInt(stat.getSelectedItem().toString()) == 4)
            {
                apib.add(HopkinsCourse.getCourse("550.111"));
            }
           
        }
        
        //IB Bio
         if (!(ibBio.getSelectedItem().toString().trim().equals(("N/A").trim())))
        {
            if (Integer.parseInt(ibBio.getSelectedItem().toString()) == 6 || Integer.parseInt(ibBio.getSelectedItem().toString()) == 7)
            {
                apib.add(HopkinsCourse.getCourse("020.151"));
                apib.add(HopkinsCourse.getCourse("020.152"));
                apib.add(HopkinsCourse.getCourse("020.153"));
                apib.add(HopkinsCourse.getCourse("020.154"));
            }
           
        }
        
         //IB Chem
         if (!(ibChem.getSelectedItem().toString().trim().equals(("N/A").trim())))
        {
            if (Integer.parseInt(ibChem.getSelectedItem().toString()) == 6 || Integer.parseInt(ibChem.getSelectedItem().toString()) == 7)
            {
                apib.add(HopkinsCourse.getCourse("030.101"));
                apib.add(HopkinsCourse.getCourse("030.102"));
                apib.add(HopkinsCourse.getCourse("030.105"));
                apib.add(HopkinsCourse.getCourse("030.106"));
            }
           
        }
         
         //IB Comp Sci
         if (!(ibComp.getSelectedItem().toString().trim().equals(("N/A").trim())))
        {
            if (Integer.parseInt(ibComp.getSelectedItem().toString()) == 6 || Integer.parseInt(ibComp.getSelectedItem().toString()) == 7)
            {
                apib.add(HopkinsCourse.getCourse("600.107"));
            }
           
        }
         
         //IB MacroEcon
         if (!(ibMacEcon.getSelectedItem().toString().trim().equals(("N/A").trim())))
        {
            if (Integer.parseInt(ibMacEcon.getSelectedItem().toString()) == 7)
            {
                apib.add(HopkinsCourse.getCourse("180.101"));
            }
           
        }
         
         //IB MicroEcon
         if (!(ibMicEcon.getSelectedItem().toString().trim().equals(("N/A").trim())))
        {
            if (Integer.parseInt(ibMicEcon.getSelectedItem().toString()) == 7)
            {
                apib.add(HopkinsCourse.getCourse("180.102"));
            }
           
        }
         
          //IB Comp Sci
         if (!(ibMath.getSelectedItem().toString().trim().equals(("N/A").trim())))
        {
            if (Integer.parseInt(ibMath.getSelectedItem().toString()) == 6 || Integer.parseInt(ibMath.getSelectedItem().toString()) == 7)
            {
                apib.add(HopkinsCourse.getCourse("110.108"));
            }
           
        }
         
          //IB Physics
         if (!(ibPhys.getSelectedItem().toString().trim().equals(("N/A").trim())))
        {
            if (Integer.parseInt(ibPhys.getSelectedItem().toString()) == 7)
            {
                apib.add(HopkinsCourse.getCourse("171.101"));
                apib.add(HopkinsCourse.getCourse("171.102"));
                apib.add(HopkinsCourse.getCourse("173.111"));
                apib.add(HopkinsCourse.getCourse("173.112"));
            }
            else if (Integer.parseInt(ibPhys.getSelectedItem().toString()) == 6)
            {
                apib.add(HopkinsCourse.getCourse("171.101"));
                apib.add(HopkinsCourse.getCourse("173.111"));
            }
           
        }
         
         
        } 
        
        
    
    
    private void premedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_premedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_premedActionPerformed

    public String major()
    {
        String myMajor = major.getSelectedItem().toString().trim();
        if (myMajor.equals("Please select one"))
        {
           
        }
        else if (myMajor.equals("Biomedical Engineering"))
            return "majors/bme";
         else if (myMajor.equals("Molecular and Cellular Biology"))
            return "majors/molcelbio";
         else if (myMajor.equals("Materials Science Engineering"))
            return "majors/mse";
        else if (myMajor.equals("Biophysics"))
            return "majors/biophysics";
        return "Error";
    }
    
    
    public String minor()
    {
        String myMinor = minor.getSelectedItem().toString().trim();
        if (myMinor.equals("N/A"))
        {
           return "N/A";
        }
        else if (myMinor.equals("Math"))
            return "minors/math";
         else if (myMinor.equals("Computer Science Analysis"))
            return "minors/cs analysis";
         else if (myMinor.equals("Computer Science Systems"))
            return "minors/cs systems";
        else if (myMinor.equals("Computer Science Applications"))
            return "minors/cs applications";
        return "Error";
    }
    
    public ArrayList<String> category()
    {
        ArrayList<String> results = new ArrayList<String>();
        if (major().equals("Error"))
        {
            errorMessageMajor.setText("Error. Please select a Major");
            return null;
        }
        else
        {
             errorMessageMajor.setText("");
             results.add(major());
             if (!minor().equals("N/A"))
             {
                 results.add(minor());
             }
              if (premed.isSelected())
            {
              results.add("premed");
                 }
        }
       
        return results;
    }
    
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        addAPIB();
        ArrayList<String> categories = category();
        if (categories == null) return;
          HashSet<HopkinsCourse> coursesTaken = merge();
        String one, two, three;
        one = "";
        two = "";
        three = "";
        one = categories.get(0);
        if (categories.size() > 1)
        two = categories.get(1);
        
         if (categories.size() > 2)
        three = categories.get(2);
        ArrayList<HopkinsCourse> priorityCourses = new ArrayList<HopkinsCourse>();
        if (one.length() != 0)
        {
            if (two.length() != 0 && three.length() != 0)
                priorityCourses = CourseListGenerator.generateBestSchedule(coursesTaken,categories);
            else if (two.length() == 0 && three.length() != 0)
            {
                priorityCourses = CourseListGenerator.generateBestSchedule(coursesTaken,categories);
            }
            
            else if (two.length() != 0 && three.length() == 0)
            {
                priorityCourses = CourseListGenerator.generateBestSchedule(coursesTaken,categories);
            }
            else if (two.length() == 0 && three.length() == 0)
            {
                priorityCourses = CourseListGenerator.generateBestSchedule(coursesTaken,categories);
            }
        }
      double desiredCredits = Double.parseDouble(credit.getSelectedItem().toString());
      String stringSemester = term.getSelectedItem().toString().toUpperCase();
      HopkinsClass.Semester currentSemester = HopkinsClass.Semester.valueOf(stringSemester.split(" ",2)[0]);
      String toSet = "Top priority courses: " + priorityCourses.toString().replace("[", "").replace("]", "");
      if (toSet.length()>143) toSet = toSet.substring(0,140) + "...";
      generatedImportantCourses.setText(toSet);
       ArrayList<HopkinsClass> finalSchedule = Schedule.matchTimes(priorityCourses, desiredCredits, currentSemester);
       String toPut = "";
       String newLn = ManageTxtFiles.newLn;
       for (HopkinsClass hc : finalSchedule) {
           toPut = toPut + HopkinsCourse.getCourse(hc.courseTitle).verbalName + " " + hc.courseTitle + " (" + hc.getSection() + ") " + hc + newLn;
       }
       scheduleDisplayer.setText(toPut);
    }//GEN-LAST:event_submitActionPerformed

    
    
    private HashSet<HopkinsCourse> takenCourses = new HashSet<HopkinsCourse>();
    
    public HashSet<HopkinsCourse> getTakenCourses() { return takenCourses; }
    public HashSet<HopkinsCourse> getAPIB() { return apib; }
    
    public HashSet<HopkinsCourse> merge()
    {
         HashSet<HopkinsCourse> results = getTakenCourses();
         HashSet<HopkinsCourse> other = getAPIB();
             
         for (HopkinsCourse a : other)
         {
             if (!results.contains(a))
                 results.add(a);
         }
        
        return results;
    }
    
    private void addTakenCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTakenCoursesActionPerformed
        // TODO add your handling code here:
        try{
        ManageTxtFiles.getAllCourses();
        }
        catch(IOException e){
     
        }
        String courseTaken = takenCourse.getText().trim();
        try{
        HopkinsCourse course = HopkinsCourse.getCourse(courseTaken);
        if (course == null)
            errorMessage.setText("Error, class doesn't exist");
        else
        {
            errorMessage.setText("");
            accepted.setText("Added");
            takenCourse.setText("");
            takenCourses.add(course);
        }
        }
        catch(Error e){
           
        }
    }//GEN-LAST:event_addTakenCoursesActionPerformed

    private void takenCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takenCourseActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_takenCourseActionPerformed

    private void statActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statActionPerformed

    private void physMechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_physMechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_physMechActionPerformed

    private void enviroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enviroActionPerformed

    private void calcABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcABActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_calcABActionPerformed

    private void micEconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_micEconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_micEconActionPerformed

    private void compABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compABActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compABActionPerformed

    private void compAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compAActionPerformed

    private void macEconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_macEconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_macEconActionPerformed

    private void bioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bioActionPerformed

    private void chemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chemActionPerformed

    private void calcBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcBCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calcBCActionPerformed

    private void physElecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_physElecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_physElecActionPerformed

    private void QuitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_QuitMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        takenCourses = new HashSet();   
        scheduleDisplayer.setText("");
        generatedImportantCourses.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void takenCourseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_takenCourseFocusGained
        if (takenCourse.getText().startsWith("Example")) takenCourse.setText("");
    }//GEN-LAST:event_takenCourseFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepageUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem QuitMenuItem;
    private javax.swing.JLabel accepted;
    private java.awt.Button addTakenCourses;
    private javax.swing.JComboBox bio;
    private javax.swing.JComboBox calcAB;
    private javax.swing.JComboBox calcBC;
    private javax.swing.JComboBox chem;
    private javax.swing.JComboBox compA;
    private javax.swing.JComboBox compAB;
    private javax.swing.JComboBox credit;
    private javax.swing.JComboBox enviro;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JLabel errorMessageMajor;
    private javax.swing.JLabel generatedImportantCourses;
    private javax.swing.JComboBox ibBio;
    private javax.swing.JComboBox ibChem;
    private javax.swing.JComboBox ibComp;
    private javax.swing.JComboBox ibMacEcon;
    private javax.swing.JComboBox ibMath;
    private javax.swing.JComboBox ibMicEcon;
    private javax.swing.JComboBox ibPhys;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Label label1;
    private javax.swing.JComboBox macEcon;
    private javax.swing.JComboBox major;
    private javax.swing.JComboBox micEcon;
    private javax.swing.JComboBox minor;
    private javax.swing.JComboBox physElec;
    private javax.swing.JComboBox physMech;
    private javax.swing.JCheckBox premed;
    private javax.swing.JPanel schedule;
    private javax.swing.JTextArea scheduleDisplayer;
    private javax.swing.JComboBox stat;
    private javax.swing.JButton submit;
    private javax.swing.JTextField takenCourse;
    private javax.swing.JComboBox term;
    // End of variables declaration//GEN-END:variables
}
